import { build } from 'esbuild';
await build({ entryPoints: ['workers/mailbox/src/worker.js'], outfile: 'workers/mailbox/dashboard-worker.js', bundle: true, format: 'esm', platform: 'browser', target: 'es2022', legalComments: 'eof', banner: { js: '// Nalaro Mailbox — dashboard-ready ES module. Generated by npm run build:mailbox.\n// Bind private R2 as MAIL_BUCKET; configure environment variables and RESEND_API_KEY secret.\n// Source: workers/mailbox/src/worker.js. Do not hand-edit this generated file.' } });
console.log('Dashboard Worker ready: workers/mailbox/dashboard-worker.js');
